### PR TITLE
Add pulsar-scenario

### PR DESCRIPTION
**Pull request by codelipenghui**
Please fill up those following information before send Pull request 

* Pull request NO: https://github.com/apache/skywalking/pull/3476
* Agent repository URL: https://github.com/codelipenghui/skywalking branch:pulsar-plugin
* Testcases repository URL: https://github.com/codelipenghui/agent-auto-integration-testcases

### CODE REVIEW

**Comment by codelipenghui** [comment]
Integration test for https://github.com/apache/skywalking/pull/3476

**Comment by codelipenghui** [comment]
How can i get the report of pulsar plugin integration tests?

**Comment by wu-sheng** [comment]
> How can i get the report of pulsar plugin integration tests?

Do you mean run local or in our project INFRA?

**Comment by codelipenghui** [comment]
> Do you mean run local or in our project INFRA?

In our project INFRA, what else do I need to do? firstly, i need to run local and tests passed and what the next? I see some test reports [here](https://github.com/SkyAPMTest/agent-integration-test-report), does this need to be triggered by other programs?

**Comment by wu-sheng** [comment]
> In our project INFRA, what else do I need to do? firstly, i need to run local and tests passed and what the next? I see some test reports here, does this need to be triggered by other programs?

You need to run locally, and post the local console logs(result part) to the plugin PR. Then we will ask one committer to manually trigger the test on the project INFRA. After that, you will see the report.

**Comment by codelipenghui** [comment]
> You need to run locally, and post the local console logs(result part) to the plugin PR. Then we will ask one committer to manually trigger the test on the project INFRA. After that, you will see the report.

Got it, thanks for the help.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
