### PR TITLE
undertow agent test

### PR DESCRIPTION
**Pull request by cloudgc**
self test result 

| Case description | Status | Cases|
|:-----|:-----:|:-----:|
|Undertow| **1 passed. 0 failed**| [click me](#undertow) |

### CODE REVIEW

**Comment by wu-sheng** [comment]
Wonderful works. @ascrutae please help on this pr.

**Comment by wu-sheng** [comment]
@cloudgc consider add more versions supported tests?

**Comment by cloudgc** [comment]
I am on it 

-------------
From cloudgc

发件人: 吴晟 Wu Sheng
发送时间: 2018年8月13日 18:39
收件人: SkywalkingTest/skywalking-agent-testcases
抄送: cloudgc; Mention
主题: Re: [SkywalkingTest/skywalking-agent-testcases] undertow agent test(#23)

@cloudgc consider add more versions supported tests?

**Comment by wu-sheng** [comment]
Have you run the cases on your local?

**Comment by wu-sheng** [comment]
@cloudgc Look like your new codes CI fails.

**Pull request closed without merging**
