### PR TITLE
Fix add rabbitmq  test case

### PR DESCRIPTION
**Pull request by withlin**
Please fill up those following information before send Pull request 

* Pull request NO: #1717
* Agent repository URL: https://github.com/WithLin/incubator-skywalking.git
* Testcases repository URL: https://github.com/WithLin/skywalking-agent-testcases.git

### CODE REVIEW

**Review by ascrutae — COMMENTED** [review]
I found the `BROKEN_URL` value is incorrect when the scenario running in docker. because the rabbitMQ server and the scenario application isn't run in one container. so The `BROKEN_URL ` cannot use `127.0.0.1`, and this is the root cause about all test case failed

**Comment by withlin** [comment]
Thank you for your reminder, i try to fix  it.

**Comment by withlin** [comment]
I am  fixed  it. you can codereview what I modified and then run the test.

**Comment by ascrutae** [comment]
Got it. the test case is running

**Comment by withlin** [comment]
sorry.I forgot the previous undertow plugin, causing my except data not modified. please you run the test case again.

**Pull request closed without merging**
