### PR TITLE
spring-cloud-gateway traceid does not transmit. pull request 3446,BUG…

### PR DESCRIPTION
**Pull request by hi-sb**
Please fill up those following information before send Pull request 

* Pull request NO: https://github.com/apache/skywalking/pull/3446 3446
* Agent repository URL: https://github.com/hi-sb/skywalking.git  branch: master
* Testcases repository URL: https://github.com/hi-sb/agent-auto-integration-testcases.git branch: master

### CODE REVIEW

**Comment by hi-sb** [comment]
Sorry,We just started using "skywalking".I'm not too familiar with the other plug-ins he owns. I updated my use case.

**Comment by zhaoyuguang** [comment]
@hi-sb   don't remove @Component annotation and in `skywalking-agent-testcases/gateway-scenario/projectA/docker/startup.sh` line5 add
```rm -rf ${AGENT_FILE_PATH}/plugins/apm-spring-annotation-plugin-*.jar ```

**Comment by hi-sb** [comment]
What do you mean, what else do I need to do?

**Comment by hi-sb** [comment]
@zhaoyuguang What do you mean, what else do I need to do?

**Comment by hi-sb** [comment]
@zhaoyuguang I have added a command to delete dependency “apm-spring-annotation-plugin-*.jar”

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
