### PR TITLE
Support RESTEasy plugin scenario

### PR DESCRIPTION
**Pull request by yanfch**
Please fill up those following information before send Pull request 

* Pull request NO: #2665 https://github.com/apache/skywalking/pull/2665
* Agent repository URL: https://github.com/yanfch/skywalking.git
* Testcases repository URL: https://github.com/yanfch/agent-auto-integration-testcases.git

### CODE REVIEW

**Comment by wu-sheng** [comment]
Is this PR ready to test?

**Comment by yanfch** [comment]
What am I going to do next?  The dev env test passed.

**Comment by wu-sheng** [comment]
@ascrutae Please review the test case.

**Comment by wu-sheng** [comment]
@IanCao Is this plugin ready to test?

**Review by IanCao — DISMISSED** [review]
LGTM

**Review by wu-sheng — CHANGES_REQUESTED** [review]
I suggest making this scenario more complex, because, you haven't test the context propagation through header.

**Comment by wu-sheng** [comment]
You at least should create `App1(resteasy, httpclient) -> App2(resteasy)`, then you could test trace go through with and without header.

**Comment by wu-sheng** [comment]
Is this test case ready to go?

**Comment by yanfch** [comment]
Ready. 😁

**Comment by IanCao** [comment]
inline

**Review by wu-sheng — APPROVED** [review]

**Review by ascrutae — APPROVED** [review]

**Pull request merged**
