### PR TITLE
Add [Agent] Jedis LETTUCE client plugin testcase

### PR DESCRIPTION
**Pull request by lytscu**
Describe the details and related test reports.
https://github.com/SkywalkingTest/agent-integration-test-report/blob/master/2018/2/lytscu/testReport-master-2018-02-27-09-16.md

### CODE REVIEW

**Comment by ascrutae** [comment]
Could you add `async` operation into test case controller? I want to know what the trace look like by using the async way to operate Redis

**Comment by ascrutae** [comment]
Cloud you post the latest test report ?

**Comment by lytscu** [comment]
https://github.com/SkywalkingTest/agent-integration-test-report/blob/master/2018/2/lytscu/testReport-master-2018-02-28-11-50.md

**Comment by lytscu** [comment]
https://github.com/SkywalkingTest/agent-integration-test-report/blob/master/2018/3/lytscu/testReport-master-2018-03-01-10-50.md

**Comment by wu-sheng** [comment]
@ascrutae What is the status of this pr?

**Comment by wu-sheng** [comment]
Closing this, no update more than 3 months.

**Pull request closed without merging**
