### PR TITLE
Kafka plugin tests

### PR DESCRIPTION
**Pull request by stalary**
Please fill up those following information before send Pull request 

* Pull request NO: https://github.com/apache/skywalking/pull/3390
* Agent repository URL: https://github.com/stalary/skywalking   branch:kafka_compate
* Testcases repository URL: https://github.com/stalary/agent-auto-integration-testcases 

[INFO] ---------------------------Here is the test report context -------------------------------------
# Test Report - 2019-09-02 12:17

- tests  : **16 passed**. **0 failed**
- branch name : **[kafka_compate](https://github.com/apache/incubator-skywalking/tree/kafka_compate)**
- commit id : **[cd8a2e7de238796fe53e732bace6c63046f0c043](https://github.com/apache/incubator-skywalking/commit/cd8a2e7de238796fe53e732bace6c63046f0c043)**
- cases branch: **[master](https://github.com/SkywalkingTest/skywalking-autotest-scenarios/tree/master)**
- cases commit id: **[5c163c151a0e3a1e222284a116b312ac16f7dbe3](https://github.com/SkywalkingTest/skywalking-autotest-scenarios/commit/5c163c151a0e3a1e222284a116b312ac16f7dbe3)**

## Cases List

| Case description | Status | Cases|
|:-----|:-----:|:-----:|
|Kafka| **16 passed. 0 failed**| [click me](#kafka) |
### 
|  Version     | Passed | Failed|
|:------------- |:-------:|:-----:|
| 0.11.0.0  | :heavy_check_mark:||
| 0.11.0.1  | :heavy_check_mark:||
| 0.11.0.2  | :heavy_check_mark:||
| 0.11.0.3  | :heavy_check_mark:||
| 1.0.1  | :heavy_check_mark:||
| 1.0.2  | :heavy_check_mark:||
| 1.0.0  | :heavy_check_mark:||
| 1.1.0  | :heavy_check_mark:||
| 1.1.1  | :heavy_check_mark:||
| 2.0.0  | :heavy_check_mark:||
| 2.0.1  | :heavy_check_mark:||
| 2.1.0  | :heavy_check_mark:||
| 2.1.1  | :heavy_check_mark:||
| 2.2.0  | :heavy_check_mark:||
| 2.2.1  | :heavy_check_mark:||
| 2.3.0  | :heavy_check_mark:||

[INFO] -----------------------------------end the report-----------------------------------------------

### CODE REVIEW

**Comment by wu-sheng** [comment]
Are 2.1.1+ passing now?

**Comment by stalary** [comment]
> Are 2.1.1+ passing now?

Not yet. I'll check it out if I have time today

**Comment by stalary** [comment]
> Are 2.1.1+ passing now?

All passed

**Review by kezhenxu94 — APPROVED** [review]
LGTM

**Comment by kezhenxu94** [comment]
apache/skywalking#3390 is merged, let's merge this to run the tests for Kafka plugin daily

**Pull request merged**
